# Generated by Django 4.2.4 on 2023-08-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_isbn',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_publish_date',
            new_name='publish_date',
        ),
    ]
